[user]
name = "Hass Khalid"

[signing]
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBRg9FKa03UuS/SPokIVQdfA7GMlHyjvTQRf6oPzAegY"
behavior = "own"
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[ui]
default-command = "log"
pager = ":builtin"

[revsets]
log = "present(@) | ancestors(immutable_heads().., 10) | present(trunk())"
